# Generated by Django 5.1.1 on 2024-09-30 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='imagen',
        ),
    ]
